export const siteConfig = {
  title: '曲言',
  subtitles: [
    '写代码，也写点别的。',
    'Stay hungry, stay foolish.',
    '代码是诗，逻辑是韵。',
    'less is more.',
    '在 0 和 1 之间找答案。',
    'bug 是暂时的，优雅是永恒的。',
    'Talk is cheap. Show me the code.',
    '一杯茶，一行代码，一个下午。',
    'Make it work, make it right, make it fast.',
    'First, solve the problem.',
    '没有银弹，但有热更新。',
    '// TODO: 写一条有意思的副标题',
    'Convention over configuration.',
    '删代码比写代码快乐。',
    'The best code is no code.',
    '人生苦短，用 TypeScript。',
    '白天的 bug 晚上修。',
    'refactor: 重构人生',
    '404: 灵感 not found',
    'Keep it simple, stupid.',
    '夜深了，编译器还在工作。',
    '所有伟大的项目都始于一个 README。',
    'git commit -m "fix: 又一个凌晨三点"',
    'Move fast and don\'t break things.',
  ],
  description: '基于 Vue 3、Element Plus 与 Markdown 构建的静态个人博客。',
  author: 'quyansiyuanwang',
  repoName: 'PersonalBlog',
  siteUrl: 'https://blog.qysyw.cn/',
  basePath: import.meta.env.BASE_URL,
  locale: 'zh_CN',
  hero: '',
  signature: '',
  location: '浙江',
  email: 'quyansiyuanwang@qq.com',
  avatar: `${import.meta.env.BASE_URL}avatar-cover.svg`,
  cover: `${import.meta.env.BASE_URL}avatar-cover.svg`,
  socialImage: `${import.meta.env.BASE_URL}avatar-cover.svg`,
  keywords: ['个人博客', 'Vue', '前端', 'Markdown'],
}
