export const siteConfig = {
  title: '曲言',
  subtitle: '写代码，也写点别的。',
  description: '基于 Vue 3、Element Plus 与 Markdown 构建的静态个人博客。',
  author: 'quyansiyuanwang',
  repoName: 'PersonalBlog',
  siteUrl: 'https://blog.qysyw.cn/',
  basePath: import.meta.env.BASE_URL,
  locale: 'zh_CN',
  hero: '',
  signature: '',
  location: '浙江',
  email: 'quyansiyuanwang@qq.com',
  avatar: `${import.meta.env.BASE_URL}avatar-cover.svg`,
  cover: `${import.meta.env.BASE_URL}avatar-cover.svg`,
  socialImage: `${import.meta.env.BASE_URL}avatar-cover.svg`,
  keywords: ['个人博客', 'Vue', '前端', 'Markdown'],
}
